ROLE_ADMIN = "admin"
ROLE_CIRCLE_COORDINATOR = "Circlecoordinator"
ROLE_SURVEY_COORDINATOR = "Surveycoordinator"
ROLE_DESIGN_COORDINATOR = "designcoordinator"

ALL_ROLES = [
    ROLE_CIRCLE_COORDINATOR,
    ROLE_SURVEY_COORDINATOR,
    ROLE_DESIGN_COORDINATOR,
]
